SistemaCajaRegistradora/Controllers/MovimientoCajaController.cs
using SistemaCajaRegistradora.Models;
using SistemaCajaRegistradora.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace SistemaCajaRegistradora.Controllers
{
    public class MovimientoCajaController : Controller
    {
        private readonly ModelData db = new ModelData();

        [HttpGet]
        [ActionName("Listar")]
        public ActionResult Listar()
        {
            try
            {
                List<vmUsuario> cajeros = db.Usuarios.Select(x => new vmUsuario()
                {
                    id = x.id,
                    nombreCajero = x.nombre.Trim() + " " + x.apellido.Trim()
                }).ToList();

                ViewBag.cajerosid = new SelectList(cajeros, "id", "nombreCajero");
                return View();
            }
            catch (Exception)
            {
                return View();
            }
            
        }

        [HttpGet]
        [ActionName("getMovCaja")]
        public JsonResult getMovCaja(int? id)
        {
            vmMovimientosCaja[] mcList = db.MovimientosCajas.Include(mc => mc.Caja)
                .Where(mc => mc.cajeroid == id)
                .Select(mc => new vmMovimientosCaja()
                {
                    id = mc.id,
                    diferencia = mc.diferencia_caja,
                    fecha_apertura = mc.fecha_apertura,
                    fecha_cierre = mc.fecha_cierre,
                    monto_apertura = mc.monto_apertura,
                    num_caja = mc.Caja.num_caja,
                    total_real_efectivo = mc.total_caja_real_efectivo,
                    total_real_transferencia = mc.total_caja_real_transferencia,
                    total_venta_diaria = mc.total_venta_diaria
                })
                .ToArray();
            return Json(new
            {
                movimientos = mcList
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [ActionName("getFechaApertura")]
        public JsonResult getFechaApertura()
        {
            Usuario user = (Usuario)Session["User"];
            var lastMC = db.MovimientosCajas.Include(mc => mc.Usuario)
                                    .OrderByDescending(mc => mc.fecha_apertura)
                                    .FirstOrDefault(mc => mc.cajeroid == user.id);
            if (lastMC == null) return Json(null, JsonRequestBehavior.AllowGet);
            return Json(lastMC.fecha_apertura.AddDays(1).ToString("MM-dd-yyyy HH:mm:ss"), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [ActionName("AbrirCaja")]
        public ActionResult AbrirCaja()
        {
            try
            {
                Usuario user = (Usuario)Session["User"];
                var cajero = db.Usuarios.FirstOrDefault(u => u.id == user.id);
                if (cajero == null) throw new Exception("No existe el cajero");

                string nombreCajero = cajero.nombre.Trim() + " " + cajero.apellido.Trim();
                var cajas = db.Cajas.ToList();
                ViewBag.cajero = nombreCajero;
                ViewBag.cajas = new SelectList(cajas, "id", "num_caja");
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("AbrirCaja");
            }
            
        }

        [HttpPost]
        [ActionName("AbrirCaja")]
        public ActionResult AbrirCaja(DateTime fecha, string monto, int cajas)
        {
            //Verificar valores
            if (fecha == null && string.IsNullOrEmpty(monto)) return RedirectToAction("AbrirCaja");
            // Obtener usuario actual
            Usuario user = (Usuario)Session["User"];
            //Verifico si la caja esta en uso
            if (verificarCajaUso(cajas))
            {
                TempData["msgError"] = "La caja seleccionada esta siendo utilizada por otro cajero";
                return RedirectToAction("AbrirCaja");
            }
            //Verifico si se debe realizar apertura de caja
            if (!verificarAperturaCaja())
            {
                return RedirectToAction("POS", "Venta");
            }
            using (TransactionScope scope = new TransactionScope())
            {
                using (ModelData db1 = new ModelData())
                {
                    try
                    {
                        //Convierto el monto a entero, remplazando los puntos a vacio
                        int montoapertura = Convert.ToInt32(monto.Replace(".", ""));

                        MovimientosCaja mc = new MovimientosCaja()
                        {
                            fecha_apertura = fecha,
                            monto_apertura = montoapertura,
                            cajaid = cajas,
                            cajeroid = user.id
                        };
                        db.MovimientosCajas.Add(mc);
                        int n = db.SaveChanges();
                        //Si no se guardaron los cambios, lo mando a la vista nuevamente
                        if (n == 0)
                            throw new Exception("No se guardo ningun cambio, asegurese de que los datos ingresados son correctos");
                        //Transaccion completada
                        scope.Complete();

                        return RedirectToAction("POS", "Venta");
                    }
                    catch (Exception e)
                    {
                        TempData["msgError"] = e == null ? 
                            "Ha ocurrido un error inesperado, asegurese de que los datos ingresados son correctos"
                            :e.ToString();
                        return RedirectToAction("AbrirCaja");
                    }
                }
            }

        }

        [HttpGet]
        [ActionName("CerrarCaja")]
        public ActionResult CerrarCaja()
        {
            DateTime lastDate = DateTime.Now;
            Usuario user = (Usuario)Session["User"];
            //Se consigue los datos del cajero y ultimo movimiento de caja
            var cajero_mc_data = db.Usuarios.Include(u => u.MovimientosCajas)
                .Where(u => u.id == user.id)
                .Select(u => new
                    {
                        nombreCajero = u.nombre.Trim() + " " + u.apellido.Trim(),
                        lastMC = u.MovimientosCajas.OrderByDescending(mc => mc.fecha_apertura)
                                .FirstOrDefault()
                    })
                .FirstOrDefault();
            //Se verifica si existen los datos del usuario
            if (cajero_mc_data == null || string.IsNullOrEmpty(cajero_mc_data.nombreCajero))
            {
                TempData["msgError"] = "No existe ningun cajero, asegurese que este iniciado de sesion antes de realizar el proceso, o reinicie el sistema";
                return RedirectToAction("POS", "Venta");
            }

            var lastMC = cajero_mc_data.lastMC;

            //Calcular el total de venta
            int totalVentasDia = db.Ventas.Include(v => v.MovimientosCaja)
                .Any(v =>
                    v.MovimientosCaja.cajeroid == user.id
                    && v.fecha_creacion >= lastMC.fecha_apertura
                    && v.fecha_creacion <= lastDate)
                ? db.Ventas.Where(v =>
                    v.MovimientosCaja.cajeroid == user.id
                    && v.fecha_creacion >= lastMC.fecha_apertura
                    && v.fecha_creacion <= lastDate).Sum(v => v.total_venta) : 0;

            if (totalVentasDia == 0)
            {
                TempData["msgError"] = "No existe ninguna venta, al menos debe haber una venta realizada para el cierre de caja";
                return RedirectToAction("POS","Venta");
            }

            vmCerrarCaja cc = new vmCerrarCaja()
            {
                totalVentaDia = totalVentasDia,
                montoAperturaCaja = lastMC.monto_apertura,
                total = totalVentasDia + lastMC.monto_apertura,
                fecha_cc = lastDate,
                fecha_ac = lastMC.fecha_apertura
            };
            ViewBag.cajero = cajero_mc_data.nombreCajero;
            return View(cc);
        }

        [HttpPost]
        [ActionName("CerrarCaja")]
        public ActionResult CerrarCaja(DateTime fecha_cc, int total, int montoRealEfectivo,
                                    int montoRealTransferencia, int diferencia)
        {
            Usuario user = (Usuario)Session["User"];
            var lastMC = db.MovimientosCajas.Include(mc => mc.Usuario)
                .OrderByDescending(mc => mc.fecha_apertura)
                .FirstOrDefault(mc => mc.cajeroid == user.id);

            if (lastMC.fecha_cierre == null)
            {
                lastMC.total_caja_real_efectivo = montoRealEfectivo;
                lastMC.total_caja_real_transferencia = montoRealTransferencia;
                lastMC.total_venta_diaria = total;
                lastMC.diferencia_caja = diferencia;
                lastMC.fecha_cierre = fecha_cc;

                db.Entry(lastMC).State = EntityState.Modified;
                int n = db.SaveChanges();
                if (n != 0)
                {
                    return RedirectToAction("POS", "Venta");
                }
                return View();
            }
            return RedirectToAction("POS", "Venta");
        }

        private bool verificarCajaUso(int cajas)
        {
            var movimientosCajas = db.MovimientosCajas.Where(mc => mc.fecha_cierre == null).ToArray();

            if (movimientosCajas.Length == 0)
            {
                return false;
            }
            return movimientosCajas.Select(mc => mc.cajaid == cajas).SingleOrDefault();
        }

        private bool verificarAperturaCaja()
        {
            DateTime datetime = DateTime.Now;

SistemaCajaRegistradora/Views/MovimientoCaja/AbrirCaja.cshtml
@{
    ViewBag.Title = "Apertura de caja";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Topbar  -->
<nav class="navbar navbar-expand navbar-light bg-white mb-4 topbar shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span id="text_nameuser" class="mr-2 d-none d-md-inline text-gray-600 fw-bold">Cargando...</span>
                <img id="img_user" class="img-profile rounded-circle img-fluid"
                     src="~/Assets/images/blank-profile.png">
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a id="linksChangePass" class="dropdown-item" href="javascript:;">Cambiar contraseña</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a id="linksignout" class="dropdown-item text-danger" href="javascript:;">Cerrar sesion</a></li>
            </ul>
        </li>
    </ul>
</nav>
<!-- End of Topbar -->
<div class="container-fluid">
    @if (TempData["msgError"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            @TempData["msgError"]
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    <div class="row justify-content-between">
        <div class="col-4">
            <h1 class="h3 mb-4 text-gray-800">@ViewBag.Title</h1>
        </div>
    </div>
    <form id="form_opencaja" action="@Url.Action("AbrirCaja","MovimientoCaja")" method="post">
        <div class="mb-3 row">
            <label for="staticDate" class="col-sm-2 col-form-label">Fecha apertura:</label>
            <div class="col-sm-10">
                <input type="text" name="fecha" readonly class="form-control-plaintext" id="staticDate" value="@DateTime.Now">
            </div>
        </div>
        <div class="mb-3 row">
            <label for="staticCajero" class="col-sm-2 col-form-label">Nombre cajero:</label>
            <div class="col-sm-10">
                <input type="text" name="cajero" readonly class="form-control-plaintext" id="staticCajero" value="@ViewBag.cajero">
            </div>
        </div>
        <div class="mb-3 row">
            <label for="selectCaja" class="col-sm-2 col-form-label">Numero de caja:</label>
            <div class="col-sm-10">
                @Html.DropDownList("cajas", null, "Seleccione el numero de la caja",
                        htmlAttributes: new { @class = "form-select", @required = "required" })
            </div>
        </div>
        <div class="mb-3 row">
            <label for="inputMonto" class="col-sm-2 col-form-label">Monto apertura:</label>
            <div class="col-sm-10 input-group mb-3">
                <span class="input-group-text">$</span>
                <input type="text" class="form-control" name="monto" id="inputMonto" value="0">
            </div>
        </div>
        <button type="submit" class="btn btn-primary mb-3">Abrir Caja</button>

    </form>
</div>
@section js{
<script type="text/javascript" src="~/Scripts/js/aperturacajascript.js"></script>
}

SistemaCajaRegistradora/Views/MovimientoCaja/CerrarCaja.cshtml
@model SistemaCajaRegistradora.Models.ViewModels.vmCerrarCaja
@{
    ViewBag.Title = "Cierre de Caja";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Topbar  -->
<nav class="navbar navbar-expand navbar-light bg-white mb-4 topbar shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span id="text_nameuser" class="mr-2 d-none d-md-inline text-gray-600 fw-bold">Cargando...</span>
                <img id="img_user" class="img-profile rounded-circle img-fluid"
                     src="~/Assets/images/blank-profile.png">
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a id="linksChangePass" class="dropdown-item" href="javascript:;">Cambiar contraseña</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a id="linksignout" class="dropdown-item text-danger" href="javascript:;">Cerrar sesion</a></li>
            </ul>
        </li>
    </ul>
</nav>
<!-- End of Topbar -->
<div class="container-fluid">
    <div class="row justify-content-between">
        <div class="col-4">
            <h1 class="h3 mb-4 text-gray-800">@ViewBag.Title</h1>
        </div>
    </div>
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-danger d-flex align-items-center alert-dismissible fade show" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill" /></svg>
            <div>
                @TempData["mensaje"]
            </div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    <form id="form_closecaja" action="@Url.Action("CerrarCaja","MovimientoCaja")" method="post">
        <div class="row">
            <div class="col-lg-6">
                <div class="mb-3 row">
                    <label for="staticDateA" class="col-sm-3 col-form-label fw-bold">Fecha de apertura:</label>
                    <div class="col-sm-9">
                        <input type="text" name="fecha_ac" readonly class="form-control"
                               aria-label="readonly input example" id="staticDateA" value="@Model.fecha_ac">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="staticDateC" class="col-sm-3 col-form-label fw-bold">Fecha de cierre:</label>
                    <div class="col-sm-9">
                        <input type="text" name="fecha_cc" readonly class="form-control"
                               aria-label="readonly input example" id="staticDateC" value="@Model.fecha_cc">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="staticCajero" class="col-sm-3 col-form-label fw-bold">Nombre cajero:</label>
                    <div class="col-sm-9">
                        <input type="text" readonly class="form-control"
                               aria-label="readonly input example" id="staticCajero" value="@ViewBag.cajero">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="inputSalesDay" class="col-sm-3 col-form-label fw-bold text-truncate">Total venta:</label>
                    <div class="col-sm-9 input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="text" name="totalventa" readonly class="form-control"
                               aria-label="readonly input example" id="inputSalesDay" value="@Model.totalVentaDia">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="inputMonto" class="col-sm-3 col-form-label fw-bold text-truncate">Monto apertura:</label>
                    <div class="col-sm-9 input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="text" class="form-control" readonly name="monto_a"
                               aria-label="readonly input example" id="inputMonto" value="@Model.montoAperturaCaja">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="inputTotal" class="col-sm-3 col-form-label fw-bold">Total en caja:</label>
                    <div class="col-sm-9 input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="text" class="form-control" readonly name="total"
                               aria-label="readonly input example" id="inputTotal" value="@Model.total">
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="mb-3 row">
                    <label for="inputMontoRealEfectivo" class="col-sm-3 col-form-label fw-bold">Monto real efectivo:</label>
                    <div class="col-sm-9 input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="text" class="form-control" name="montoRealEfectivo" id="inputMontoRealEfectivo" value="0" required>
                    </div>
                    <label for="inputMontoRealTransferencia" class="col-sm-3 col-form-label fw-bold">Monto real tarjetas:</label>
                    <div class="col-sm-9 input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="text" class="form-control" name="montoRealTransferencia" id="inputMontoRealTransferencia" value="0" required>
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="inputDiferencia" class="col-sm-2 col-form-label fw-bold">Diferencia:</label>
                    <div class="col-sm-10 input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="text" class="form-control"
                               aria-label="readonly input example" name="diferencia" id="inputDiferencia" readonly value="0">
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-danger mb-3">Cerrar Caja</button>
        <a class="btn btn-outline-secondary mb-3" href="@Url.Action("POS","Venta")">Cancelar</a>

    </form>
</div>
@section js{
<script type="text/javascript" src="~/Scripts/js/cerrarcajascript.js"></script>
}

SistemaCajaRegistradora/Views/MovimientoCaja/Listar.cshtml
@{
    ViewBag.Title = "Movimientos de caja";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Topbar  -->
<nav class="navbar navbar-expand navbar-light bg-white mb-4 topbar shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span id="text_nameuser" class="mr-2 d-none d-md-inline text-gray-600 fw-bold">Cargando...</span>
                <img id="img_user" class="img-profile rounded-circle img-fluid"
                     src="~/Assets/images/blank-profile.png">
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a id="linksChangePass" class="dropdown-item" href="javascript:;">Cambiar contraseña</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a id="linksignout" class="dropdown-item text-danger" href="javascript:;">Cerrar sesion</a></li>
            </ul>
        </li>
    </ul>
</nav>
<!-- End of Topbar -->
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row justify-content-between">
        <div class="col-4">
            <h1 class="h3 mb-4 text-gray-800">@ViewBag.Title</h1>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-lg-4">
            <label for="categoriaId" class="form-label fw-bold">Cajero</label>
            @Html.DropDownList("cajerosid", null, "Seleccionar cajero",
                        htmlAttributes: new { @class = "form-select" })
        </div>
        <div class="col-lg-4">
            <div class="row">
                <label for="input_desde" class="form-label text-center fw-bold">Filtro de Fecha</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="label_desde">Desde</span>
                    <input id="input_desde" type="text" class="form-control" aria-describedby="label_desde">
                    <span class="input-group-text" id="label_hasta">Hasta</span>
                    <input id="input_hasta" type="text" class="form-control" aria-describedby="label_hasta">
                </div>
            </div>
        </div>
        <div class="col-lg-4 align-self-center">
            <div class="form-check">
                <input class="form-check-input" type="radio" name="radio_fecha" id="radio_apertura" checked value="1">
                <label class="form-check-label" for="radio_apertura">
                    Filtrar fecha apertura
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="radio_fecha" id="radio_cierre" value="2">
                <label class="form-check-label" for="radio_cierre">
                    Filtrar fecha cierre
                </label>
            </div>
        </div>
    </div>
    <!-- table -->
    <div class="row">
        <div class="col-12">
            <table id="tablaMC" class="display table table-bordered table-hover w-100">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th scope="col">N° de Caja</th>
                        <th scope="col">Monto de apertura</th>
                        <th scope="col">Fecha de apertura</th>
                        <th scope="col">Fecha de cierre</th>
                        <th scope="col">Total venta diaria</th>
                        <th scope="col">Total real efectivo</th>
                        <th scope="col">Total real transferencias</th>
                        <th scope="col">Diferencia</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th colspan="8" style="text-align:right">Total Diferencia:</th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
<!-- Modal core base-->
<div class="modal fade" id="coreModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true" data-bs-backdrop="static">
</div>
@section js{
<script src="~/Scripts/Datatable/dtMC.js"></script>
}