SistemaCajaRegistradora/Models/Venta.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCajaRegistradora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.DetalleVentas = new HashSet<DetalleVenta>();
        }
    
        public long id { get; set; }
        public int total_venta { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int vuelto { get; set; }
        public int movimientocajaid { get; set; }
        public int metodo_pagoid { get; set; }
        public int monto_ingresado { get; set; }
        public long num_boleta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVentas { get; set; }
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual MovimientosCaja MovimientosCaja { get; set; }
    }
}

SistemaCajaRegistradora/Controllers/VentaController.cs
using SistemaCajaRegistradora.Models;
using SistemaCajaRegistradora.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using SistemaCajaRegistradora.Filters;
using System.Transactions;

namespace SistemaCajaRegistradora.Controllers
{
    public class VentaController : Controller
    {
        private readonly ModelData db = new ModelData();
        private readonly int numeroBoleta = 0; //Numero de boletas
        
        // GET: Venta
        [HttpGet]
        [Autorizacion(idoperacion: 21)]
        [ActionName("Listar")]
        public ActionResult Listar() => View();

        [HttpGet]
        [Autorizacion(idoperacion: 22)]
        [ActionName("getVentas")]
        public JsonResult getVentas()
        {
            db.Configuration.LazyLoadingEnabled = false;

            List<vmVenta> ventas = db.Ventas.Include(v => v.MetodoPago)
                .Include(v => v.MovimientosCaja.Usuario)
                .Select(v => new vmVenta()
                {
                    id = v.id,
                    cajero = v.MovimientosCaja.Usuario.nombre.Trim() + " " + v.MovimientosCaja.Usuario.apellido.Trim(),
                    metodoPago = v.MetodoPago.metodo_pago.Trim(),
                    numboleta = v.num_boleta,
                    totalVenta = v.total_venta,
                    fecha = v.fecha_creacion
                }).ToList();
            return Json(new
            {
                data = ventas
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Autorizacion(idoperacion: 23)]
        [ActionName("getMoreDetail")]
        public PartialViewResult getMoreDetail(long? id)
        {
            if (id == null) return PartialView(null);

            var detailVentas = db.DetalleVentas
                                    .Include(vp => vp.Producto)
                                    .Include(vp => vp.Venta.MovimientosCaja.Usuario)
                                    .Where(vp => vp.ventaid == id).ToList();
            return PartialView("_detailVenta", detailVentas);
        }

        [HttpGet]
        [ActionName("POS")]
        public ActionResult POS()
        {
            if (verificarAperturaCaja())
            {
                return RedirectToAction("AbrirCaja","MovimientoCaja");
            }
            if (verificarCierreCaja())
            {
                TempData["mensaje"] = "Han pasado 24 horas desde la apertura de caja, se debe cerrar obligatoriamente";
                return RedirectToAction("CerrarCaja", "MovimientoCaja");
            }
            return View();
        }

        [HttpGet]
        [ActionName("ultimaVenta")]
        public JsonResult ultimaVenta()
        {
            string msgError = "No existe ninguna venta asociada al cajero";
            string msgSuccess = "Ultima venta imprimiendo...";
            
            Usuario user = (Usuario)Session["User"];
            var result = db.Ventas.Include(v => v.MetodoPago)
                                .Include(v => v.MovimientosCaja)
                                .OrderByDescending(v => v.fecha_creacion)
                                .FirstOrDefault(v => v.MovimientosCaja.cajeroid == user.id);
            if (result == null)
            {
                return Json(new
                {
                    data = 0,
                    msg = msgError
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new
            {
                data = result.id,
                msg = msgSuccess
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ActionName("cargarProducto")]
        public JsonResult cargarProducto(Producto producto)
        {
            if (producto == null)
            {
                return Json(new
                {
                    codigobarra = "",
                    mensaje = "Existe un error de conexion, reinicie la página",
                }, JsonRequestBehavior.AllowGet);
            }
            string codigo = producto.codigo_barra;
            int stock = (int)producto.stock;
            var prod = db.Productos.FirstOrDefault(p => p.codigo_barra.Equals(codigo));
            if (prod == null)
            {
                return Json(new
                {
                    codigobarra = "",
                    mensaje = "No existe ningún producto asociado a este código de barra",
                }, JsonRequestBehavior.AllowGet);
            }
            if (prod.stock <= stock)
            {
                return Json(new
                {
                    codigobarra = "",
                    mensaje = "Stock insuficiente",
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new
            {
                prod.id,
                codigobarra = prod.codigo_barra.Trim(),
                nombre = prod.nombre.Trim(),
                prod.precio,
                cantidadmax = prod.stock,
                cantidad = producto.stock,
                preciototal = 0,
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ActionName("finalizarVenta")]
        public JsonResult finalizarVenta(vmVentaDetalle ventaDetalle)
        {
            if (verificarAperturaCaja() || verificarCierreCaja())
            {
                return Json(new
                {
                    data = "",
                    idventa = -1
                }, JsonRequestBehavior.AllowGet);
            }
            using (TransactionScope scope = new TransactionScope())
            {
                string msgError = "Ocurrio un error inesperado, intentelo nuevamente o reinicie la pagina";
                string msgErrorMC = "Al parecer no existe ningun movimiento de caja o no se ha cerrado aun correctamente";
                string msgSuccess = "Venta creada correctamente";
                int n = 0;
                try
                {
                    //Se verifica si no viene vacio el objeto
                    if (ventaDetalle == null)
                    {
                        throw new Exception(msgError);
                    }
                    Usuario user = (Usuario)Session["User"];
                    var ventas_mc_data = db.Ventas.Include(v => v.MovimientosCaja).ToArray();

                    //Se verifica si no esta vacio
                    long length = ventas_mc_data.Length + 1;
                    if (length == 0)
                    {
                        throw new Exception(msgErrorMC);
                    }

                    //Buscar el ultimo movimiento de caja del cajero
                    var lastMC = ventas_mc_data
                        .OrderByDescending(v => v.MovimientosCaja.fecha_apertura)
                        .FirstOrDefault(v => v.MovimientosCaja.cajeroid == user.id).MovimientosCaja;

                    //Insercion de los datos de la venta a la base de datos
                    ventaDetalle.venta.fecha_creacion = DateTime.Now;
                    ventaDetalle.venta.movimientocajaid = lastMC.id;
                    ventaDetalle.venta.num_boleta = numeroBoleta + length; //Generar el num de la boleta
                    db.Ventas.Add(ventaDetalle.venta);

                    //Insercion de los datos del detalle a la base de datos
                    long idVenta = ventaDetalle.venta.id;
                    for (int i = 0; i < ventaDetalle.dV.Count; i++)
                    {
                        ventaDetalle.dV[i].ventaid = idVenta;
                        db.DetalleVentas.Add(ventaDetalle.dV[i]);
                        int stockProd = ventaDetalle.dV[i].total_cantidad_producto;
                        int idprod = ventaDetalle.dV[i].productoid;

                        //Se modifica las existencias de los productos afectados en la venta
                        var producto = db.Productos.Find(idprod);
                        producto.stock = producto.stock - stockProd;
                        db.Entry(producto).State = EntityState.Modified;
                    }
                    n = db.SaveChanges();
                    //Si ocurre un error al guardar los cambios, realizar un rollback
                    if (n == 0)
                    {
                        throw new Exception(msgError);
                    }

                    scope.Complete();

                    //Proceso finalizado correctamente
                    return Json(new
                    {
                        data = "OK",
                        msg = msgSuccess,
                        idventa = ventaDetalle.venta.id
                    }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception)
                {
                    return Json(new
                    {
                        data = "",
                        msg = msgError,
                        idventa = 0
                    }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpGet]
        [ActionName("viewBoletaVenta")]
        public PartialViewResult viewBoletaVenta(long? id)
        {
            if (id != null)
            {
                if (id == 0)
                {
                    long ventaid = (long)Session["ventaid"];
                    var detailVentas_noid = db.DetalleVentas
                                            .Include(vp => vp.Producto)
                                            .Include(vp => vp.Venta)
                                            .Where(vp => vp.ventaid == ventaid).ToList();
                    return PartialView("_boletaVenta", detailVentas_noid);
                }
                var detailVentas_id = db.DetalleVentas
                                        .Include(vp => vp.Producto)
                                        .Include(vp => vp.Venta)

SistemaCajaRegistradora/Views/Venta/AbrirCaja.cshtml
@{
    ViewBag.Title = "Apertura de caja";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Topbar  -->
<nav class="navbar navbar-expand navbar-light bg-white mb-4 topbar shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span id="text_nameuser" class="mr-2 d-none d-md-inline text-gray-600 fw-bold">Cargando...</span>
                <img id="img_user" class="img-profile rounded-circle img-fluid"
                     src="~/Assets/images/blank-profile.png">
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a id="linksChangePass" class="dropdown-item" href="javascript:;">Cambiar contraseña</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a id="linksignout" class="dropdown-item text-danger" href="javascript:;">Cerrar sesion</a></li>
            </ul>
        </li>
    </ul>
</nav>
<!-- End of Topbar -->
<div class="container-fluid">
    @if (TempData["msgError"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            @TempData["msgError"]
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    <div class="row justify-content-between">
        <div class="col-4">
            <h1 class="h3 mb-4 text-gray-800">@ViewBag.Title</h1>
        </div>
    </div>
    <form id="form_opencaja" action="@Url.Action("AbrirCaja","Venta")" method="post">
        <div class="mb-3 row">
            <label for="staticDate" class="col-sm-2 col-form-label">Fecha apertura:</label>
            <div class="col-sm-10">
                <input type="text" name="fecha" readonly class="form-control-plaintext" id="staticDate" value="@DateTime.Now">
            </div>
        </div>
        <div class="mb-3 row">
            <label for="staticCajero" class="col-sm-2 col-form-label">Nombre cajero:</label>
            <div class="col-sm-10">
                <input type="text" name="cajero" readonly class="form-control-plaintext" id="staticCajero" value="@ViewBag.cajero">
            </div>
        </div>
        <div class="mb-3 row">
            <label for="selectCaja" class="col-sm-2 col-form-label">Numero de caja:</label>
            <div class="col-sm-10">
                @Html.DropDownList("cajas", null, "Seleccione el numero de la caja",
                        htmlAttributes: new { @class = "form-select", @required = "required" })
            </div>
        </div>
        <div class="mb-3 row">
            <label for="inputMonto" class="col-sm-2 col-form-label">Monto apertura:</label>
            <div class="col-sm-10 input-group mb-3">
                <span class="input-group-text">$</span>
                <input type="text" class="form-control" name="monto" id="inputMonto" value="0">
            </div>
        </div>
        <button type="submit" class="btn btn-primary mb-3">Abrir Caja</button>

    </form>
</div>
<script type="text/javascript" src="~/Scripts/js/aperturacajascript.js"></script>

SistemaCajaRegistradora/Views/Venta/CerrarCaja.cshtml
@model SistemaCajaRegistradora.Models.ViewModels.vmCerrarCaja
@{
    ViewBag.Title = "Cierre de Caja";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Topbar  -->
<nav class="navbar navbar-expand navbar-light bg-white mb-4 topbar shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span id="text_nameuser" class="mr-2 d-none d-md-inline text-gray-600 fw-bold">Cargando...</span>
                <img id="img_user" class="img-profile rounded-circle img-fluid"
                     src="~/Assets/images/blank-profile.png">
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a id="linksChangePass" class="dropdown-item" href="javascript:;">Cambiar contraseña</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a id="linksignout" class="dropdown-item text-danger" href="javascript:;">Cerrar sesion</a></li>
            </ul>
        </li>
    </ul>
</nav>
<!-- End of Topbar -->
<div class="container-fluid">
    <div class="row justify-content-between">
        <div class="col-4">
            <h1 class="h3 mb-4 text-gray-800">@ViewBag.Title</h1>
        </div>
    </div>
    <form id="form_closecaja" action="@Url.Action("CerrarCaja","Venta")" method="post">
        <div class="row">
            <div class="col-lg-6">
                <div class="mb-3 row">
                    <label for="staticDateA" class="col-sm-3 col-form-label fw-bold">Fecha de apertura:</label>
                    <div class="col-sm-9">
                        <input type="text" name="fecha_ac" readonly class="form-control" 
                               aria-label="readonly input example" id="staticDateA" value="@Model.fecha_ac">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="staticDateC" class="col-sm-3 col-form-label fw-bold">Fecha de cierre:</label>
                    <div class="col-sm-9">
                        <input type="text" name="fecha_cc" readonly class="form-control" 
                               aria-label="readonly input example" id="staticDateC" value="@Model.fecha_cc">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="staticCajero" class="col-sm-3 col-form-label fw-bold">Nombre cajero:</label>
                    <div class="col-sm-9">
                        <input type="text" readonly class="form-control" 
                               aria-label="readonly input example" id="staticCajero" value="@ViewBag.cajero">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="inputSalesDay" class="col-sm-3 col-form-label fw-bold text-truncate">Total venta:</label>
                    <div class="col-sm-9 input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="text" name="totalventa" readonly class="form-control"
                               aria-label="readonly input example" id="inputSalesDay" value="@Model.totalVentaDia">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="inputMonto" class="col-sm-3 col-form-label fw-bold text-truncate">Monto apertura:</label>
                    <div class="col-sm-9 input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="text" class="form-control" readonly name="monto_a"
                               aria-label="readonly input example" id="inputMonto" value="@Model.montoAperturaCaja">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="inputTotal" class="col-sm-3 col-form-label fw-bold">Total en caja:</label>
                    <div class="col-sm-9 input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="text" class="form-control" readonly name="total"
                               aria-label="readonly input example" id="inputTotal" value="@Model.total">
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="mb-3 row">
                    <label for="inputMontoRealEfectivo" class="col-sm-3 col-form-label fw-bold">Monto real efectivo:</label>
                    <div class="col-sm-9 input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="text" class="form-control" name="montoRealEfectivo" id="inputMontoRealEfectivo" value="0" required>
                    </div>
                    <label for="inputMontoRealTransferencia" class="col-sm-3 col-form-label fw-bold">Monto real tarjetas:</label>
                    <div class="col-sm-9 input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="text" class="form-control" name="montoRealTransferencia" id="inputMontoRealTransferencia" value="0" required>
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="inputDiferencia" class="col-sm-2 col-form-label fw-bold">Diferencia:</label>
                    <div class="col-sm-10 input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="text" class="form-control"
                               aria-label="readonly input example" name="diferencia" id="inputDiferencia" readonly value="0">
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-danger mb-3">Cerrar Caja</button>
        <a class="btn btn-outline-secondary mb-3" href="@Url.Action("POS","Venta")">Cancelar</a>

    </form>
</div>
<script type="text/javascript" src="~/Scripts/js/cerrarcajascript.js"></script>

SistemaCajaRegistradora/Views/Venta/Listar.cshtml
@{
    ViewBag.Title = "Listado de ventas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Topbar  -->
<nav class="navbar navbar-expand navbar-light bg-white mb-4 topbar shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span id="text_nameuser" class="mr-2 d-none d-md-inline text-gray-600 fw-bold">Cargando...</span>
                <img id="img_user" class="img-profile rounded-circle img-fluid"
                     src="~/Assets/images/blank-profile.png">
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a id="linksChangePass" class="dropdown-item" href="javascript:;">Cambiar contraseña</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a id="linksignout" class="dropdown-item text-danger" href="javascript:;">Cerrar sesion</a></li>
            </ul>
        </li>
    </ul>
</nav>
<!-- End of Topbar -->
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row justify-content-between">
        <div class="col-4">
            <h1 class="h3 mb-4 text-gray-800">@ViewBag.Title</h1>
        </div>
    </div>
    <!-- table -->
    <div class="row">
        <div class="col-12">
            <table id="tablaVenta" class="display table table-bordered table-hover w-100">
                <thead>
                    <tr>
                        <th scope="col">Cajero</th>
                        <th scope="col">Metodo de pago</th>
                        <th scope="col">Numero Boleta</th>
                        <th scope="col">Total venta</th>
                        <th scope="col">Fecha de creacion</th>
                        <th scope="col">Detalle</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
<!-- Modal core base-->
<div class="modal fade" id="coreModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true" data-bs-backdrop="static">

</div>
@section js{
<script src="~/Scripts/js/printThis.js"></script>
<script src="~/Scripts/js/scriptVenta.js"></script>
<script src="~/Scripts/Datatable/dtVenta.js"></script>
}

SistemaCajaRegistradora/Views/Venta/ReporteProductosVendidos.cshtml
@{
    ViewBag.Title = "Reporte de los productos mas vendidos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav class="navbar navbar-expand navbar-light bg-white mb-4 topbar shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span id="text_nameuser" class="mr-2 d-none d-md-inline text-gray-600 fw-bold">Cargando...</span>
                <img id="img_user" class="img-profile rounded-circle img-fluid"
                     src="~/Assets/images/blank-profile.png">
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a id="linksChangePass" class="dropdown-item" href="javascript:;">Cambiar contraseña</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a id="linksignout" class="dropdown-item text-danger" href="javascript:;">Cerrar sesion</a></li>
            </ul>
        </li>
    </ul>
</nav>
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row justify-content-between">
        <div class="col-4">
            <h3 class="mb-4 text-gray-800">@ViewBag.Title</h3>
        </div>
    </div>
    <!-- Filter -->
    @*<div class="row">
            <div class="col-4">
                <h5 class="mb-2 text-gray-600">Rango de fecha</h5>
                <div class="input-group mb-2">
                    <span class="input-group-text" id="datemin">Fecha inicio</span>
                    <input id="text_datemin" type="text" class="form-control" aria-describedby="datemin" placeholder="Ingrese fecha inicio">
                    <span class="input-group-text" id="datemax">Fecha final</span>
                    <input id="text_datemax" type="text" class="form-control" aria-describedby="datemax" placeholder="Ingrese fecha final">
                </div>
            </div>
        </div>*@
    <!-- table -->
    <div class="row">
        <div class="col-12">
            <table id="tablaRPV" class="display table table-bordered table-hover w-100">
                <thead>
                    <tr>
                        <th scope="col" style="width: 12%">Codigo Barra</th>
                        <th scope="col" style="width: 15px">Imagen Producto</th>
                        <th scope="col" style="width: 50px">Nombre Producto</th>
                        <th scope="col" style="width: 15px">Precio Producto</th>
                        <th scope="col" style="width: 8px">Cantidad vendido</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@section js{
<script src="~/Scripts/Datatable/dtRPV.js"></script>
}

SistemaCajaRegistradora/Views/Venta/ReporteVentaDiaria.cshtml
@{
    ViewBag.Title = "Reporte de venta diaria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- Topbar  -->
<nav class="navbar navbar-expand navbar-light bg-white mb-4 topbar shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span id="text_nameuser" class="mr-2 d-none d-md-inline text-gray-600 fw-bold">Cargando...</span>
                <img id="img_user" class="img-profile rounded-circle img-fluid"
                     src="~/Assets/images/blank-profile.png">
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a id="linksChangePass" class="dropdown-item" href="javascript:;">Cambiar contraseña</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a id="linksignout" class="dropdown-item text-danger" href="javascript:;">Cerrar sesion</a></li>
            </ul>
        </li>
    </ul>
</nav>
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row justify-content-between">
        <div class="col-4">
            <h3 class="mb-4 text-gray-800">@ViewBag.Title</h3>
        </div>
    </div>
    <!-- Filter -->
    <div class="row">
        <div class="col-4">
            <h5 class="mb-2 text-gray-600">Rango de fecha</h5>
            <div class="input-group mb-2">
                <span class="input-group-text" id="datemin">Fecha inicio</span>
                <input id="text_datemin" type="text" class="form-control" aria-describedby="datemin" placeholder="Ingrese fecha inicio">
                <span class="input-group-text" id="datemax">Fecha final</span>
                <input id="text_datemax" type="text" class="form-control" aria-describedby="datemax" placeholder="Ingrese fecha final">
            </div>
        </div>
    </div>
    <!-- table -->
    <div class="row">
        <div class="col-12">
            <table id="tablaRVD" class="display table table-bordered table-hover w-100">
                <thead>
                    <tr>
                        <th scope="col">Fecha</th>
                        <th scope="col">Total venta del dia</th>
                        <th scope="col">Crecimiento</th>
                        <th scope="col">Porcentaje de crecimiento</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@section js{
<script src="~/Scripts/Datatable/dtRVD.js"></script>
}